### ISSUE TITLE
Shuttle recommends downloading insecurely

### ISSUE THREAD

**Issue by lfaraone** [ashisha/shuttle#2]
Your installation instructions open users to MITM attacks. 

All versions of Ubuntu after 12.04 LTS should have no problem with GitHub's SSL certificate, so passing `--no-check-certificate` is superfluous and does not even enhance convenience at the expense of security. It just decreases security. 

Other than that, I like the project. Thanks for making a useful tool :smile:

**Comment by ashisha** [comment]
Thanks, I have merged your fix now!
Also, added a note, just in case if github's certificates cause any troubles anytime.
